# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 230c89b34369a979d4acb2e1c3421951722ebe72636fc3c982dbe69a567e133ea9c9a001df5c7d165a1543247e6a47e053e9fbc8b5e7fbc3075fdc81f48a36a2

test:
  secret_key_base: 219023f80fccc8123985544e304902ff120f670cebd2c5d5d801e44e8859e9eca533ac15bf661eb2da3443c81828cae322b22848f8be819cfd20cd903f347454

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
